name: Build and Push Docker Image

on:
  workflow_dispatch:
  push:
    paths: 
      - 'src/backend/**'
    branches:
      - master

jobs:
  build_and_push_image:
    runs-on: ubuntu-latest

    services:
      docker:
        image: docker:dind
        options: --privileged

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Login to Docker Registry
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.CI_REGISTRY_USER }}
          password: ${{ secrets.CI_REGISTRY_PAT }}

      - name: Get current date
        id: date
        run: echo "TIMESTAMP=$(date +'%Y%m%d%H%M%S')" >> $GITHUB_ENV

      - name: Build and push Docker image
        run: |
          echo "Building image ${{ secrets.CI_REGISTRY_IMAGE }}:$TIMESTAMP-${{ github.sha }}"
          cd ./src/backend/
          docker build -t ${{ secrets.CI_REGISTRY_IMAGE }}:$TIMESTAMP-${{ github.sha }} -f Dockerfile .
          docker push ${{ secrets.CI_REGISTRY_IMAGE }}:$TIMESTAMP-${{ github.sha }}
